language:
  ruby

cache: bundler

env:
  - CPLUS_INCLUDE_PATH=/usr/include/atlas C_INCLUDE_PATH=/usr/include/atlas

rvm:
  - '2.0'
  - '2.1'
  - '2.2'
  - ruby-head

before_install:
  - gem install bundler
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-base-dev

script:
  - bundle install
  - rspec