language:
  ruby

cache: bundler

env:
  - CPLUS_INCLUDE_PATH=/usr/include/atlas C_INCLUDE_PATH=/usr/include/atlas

rvm:
  - '2.0'
  - '2.1'
  - '2.2'

before_install:
  - gem install bundler
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-base-dev
  - sudo apt-get install -y libgsl0-dev r-base r-base-dev
  - sudo Rscript -e "install.packages(c('Rserve','irr'),,'http://cran.us.r-project.org')"

script:
  - bundle install
  - bundle exec rspec